[package]
name = "hqe-vector"
version.workspace = true
edition = "2021"

[dependencies]
# Placeholder crate for future vector/embedding support
# Dependencies will be added when features are implemented
